version: "3.9"
services:
  frontend:
    build:
      context: ./ZTI-Frontend #name of dir 
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - frontend_net
  backend:
    build:
      context: ./ZTI-Backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - backend_net
networks:
  frontend_net:
    driver: bridge
  backend_net:
    driver: bridge